# creating scylla cluster
version: '3'

services:
  scylla-node1:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node1
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./pkg/infrastructure/database/scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./pkg/infrastructure/database/scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
      - "./pkg/infrastructure/database/migrations/migration.sql:/migration.sql"
      - "./pkg/infrastructure/database/migrations/migration2.sql:/migration2.sql"
    ports:
      - 9042:9042
    networks:
      web:

  scylla-node2:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node2
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./pkg/infrastructure/database/scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./pkg/infrastructure/database/scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - 9043:9042
    networks:
      web:

  scylla-node3:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node3
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./pkg/infrastructure/database/scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./pkg/infrastructure/database/scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - 9044:9042
    networks:
      web:

networks:
  web:
    driver: bridge